server:
  port: 9094
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db,redis,discoveryComposite
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://${SERVER_ADDRESS:127.0.0.1}:3306/measure_community?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${DB_USERNAME:root}
          password: ${DB_PASSWORD:root}
          driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      nacos:
        enabled: true
