server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,redis,discoveryComposite
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # 用显式路由,不自动服务发现路由
      routes:
        - id: community-info
          uri: lb://community-info
          predicates:
            - Path=/api/v1/population/**
        - id: community-portal
          uri: lb://community-portal
          predicates:
            - Path=/api/v1/portal/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/api/v1/service/**
        - id: community-welfare
          uri: lb://community-welfare
          predicates:
            - Path=/api/v1/welfare/**
        - id: community-affairs
          uri: lb://community-affairs
          predicates:
            - Path=/api/v1/affairs/**
        - id: community-auth
          uri: lb://community-auth
          predicates:
            - Path=/api/v1/auth/**
    loadbalancer: #开启负载均衡
      nacos:
        enabled: true
      retry:
        enabled: true # 启用负载均衡重试机制

springdoc:
  swagger-ui:
    urls:
      - name: 信息服务
        url: /api/v1/population/v3/api-docs
      - name: 系统配置/鉴权
        url: /api/v1/auth/v3/api-docs

global:
  switch:
    user-header-filter:
      enabled: false
